snayyar00/accessibility-widget

- api/server.ts
- api/services/allowedSites/plans-sites.service.ts
- api/services/stripe/webhooks.servive.ts
- api/utils/appSumoPromoCount.ts
- api/utils/expireUsedPromo.ts
- app/src/components/Layout/Admin.tsx
- app/src/components/Plans/Plans.tsx
- app/src/containers/Dashboard/Dashboard.tsx
- app/src/containers/Dashboard/TrialBannerAndModal.tsx
- app/src/containers/Dashboard/skeletonanalytics.tsx
- app/src/containers/SiteDetail/PlanSetting.tsx
- app/src/containers/Teams/DomainTable.tsx
- app/src/containers/Teams/Teams.tsx
> AppSumo implementation and UI revamp

- api/MODULE_ALIASES.md
- api/module-aliases.js
- api/package.json
- api/server.ts
VERY IMPORTANT
**********
This fixes the annoying changing of module alieases in dev vs prod
> refactor(api): fix the module alias about fixing

- api/package-lock.json
- api/repository/accessibility.repository.ts
- app/package-lock.json
- app/package.json
- app/src/containers/Teams/CustomizeWidget.tsx
- app/src/containers/Teams/MenuPreview.tsx
- app/src/containers/Teams/editWidget.tsx
- app/yarn.lock
> New Toggle And Colors

- api/server.ts
- api/utils/customTokenCount.ts
- app/src/components/Plans/Plans.tsx
- app/src/containers/Dashboard/TrialBannerAndModal.tsx
- Agency Plan UI changes, so 50, 100 and Unlimited Plans are shown to user
- Billing button disabled for agency and app sumo users
> Agency plan UI update

- api/helpers/compile-email-template.ts
https://webability-widget.server.techywebsolutions.com/dist/blog.html
> Fix handlebars eq

- api/package-lock.json
- api/package.json
- api/services/authentication/login.service.ts
- api/services/authentication/register.service.ts
- api/services/user/update-user.service.ts
- api/utils/sanitization.helper.ts
- api/utils/validation-errors.helper.ts
- api/validations/authenticate.validation.ts
- app/package-lock.json
- app/package.json
- app/src/components/Auth/SignUpForm.tsx
- app/src/containers/Auth/SignUp.tsx
- app/src/containers/Profile/InformationSetting.tsx
- app/src/locales/en.json
- app/src/utils/errorHandler.ts
- Linear Ticket: https://linear.app/searchbox/issue/DEV-174/malicious-name-field-input-fix-and-general-xss-protection
1. **XSS Sanitization** - `api/utils/sanitization.helper.ts`
- `sanitizeInput()` using XSS library to strip HTML/scripts
- `sanitizeUserInput()` for bulk sanitization
2. **Link Detection** - Using `linkify-it`
- `validateNoLinks()` detects URLs in name fields
- `validateNameField()` comprehensive validation
3. **Malicious Pattern Detection**
- SQL injection patterns (`SELECT`, `UNION`, etc.)
- Script injection (`javascript:`, `<script>`, etc.)
- Event handlers (`onload=`, `onclick=`, etc.)
4. **Updated Services with Sanitization:**
- ✅ `register.service.ts` - Sanitizes name & email before validation
- ✅ `login.service.ts` - Sanitizes email before validation  
- ✅ …
> validations, sanitization and malicious input prevention

- app/src/App.tsx
- app/src/components/Common/Modal.tsx
- app/src/components/Common/ReportSuccessModal.tsx
- app/src/containers/Accessibility/AccessibilityReport.tsx
- app/src/containers/ProblemReport/ProblemReport.tsx
- app/src/containers/Teams/editWidget.tsx
- app/src/features/report/reportSlice.ts
- app/src/features/rootReducer.ts
- app/src/utils/translator.ts
Enhancement
___
- Implement Redux state management for report generation
- Add global report success modal with completion notification
- Persist domain scan state across page navigation
- Add Romanian language support to translator
___
```mermaid
flowchart LR
A["User initiates scan"] --> B["Redux stores scan state"]
B --> C["Report generation process"]
C --> D["Global modal shows completion"]
D --> E["State persists across navigation"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td><strong>reportSlice.ts</strong><dd><code>Create Redux slice for report state management</code>&nbsp; &nbsp; &nbsp; …
> Persist domain scan across page navigation with completion notification

- app/src/containers/Accessibility/ReportView.tsx
Enhancement
___
- Improved mobile responsiveness across all screen sizes
- Enhanced layout flexibility with responsive padding and margins
- Optimized issue cards for better mobile display
- Added responsive controls for compliance status section
___
```mermaid
flowchart LR
A["Desktop Layout"] --> B["Responsive Breakpoints"]
B --> C["Mobile-First Design"]
C --> D["Flexible Components"]
D --> E["Enhanced UX"]
```
<tr>
<td>
<details>
<summary><strong>ReportView.tsx</strong><dd><code>Mobile responsiveness improvements for report view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> Responsivness of view report page

- app/src/components/Layout/Topbar.tsx
> dropdown UI responsiveness updated

- api/.env.example
- api/README.md
- api/validations/organization.validation.ts
- app/.env.example
- app/README.md
This pull request updates environment configurations, documentation, and validation rules to reflect changes in domain naming conventions and introduces a fallback server URL for accessibility checks. The most important changes include updating domain references across multiple files, adding a fallback server URL, and ensuring consistency in validation patterns.
* Updated the `FRONTEND_URL` and `HOST` values in `.env.example` files to use the new domain `try-webability-app.server.techywebsolutions.com.127.0.0.1.sslip.io` instead of `app.trywebability.com.127.0.0.1.sslip.io`. [[1]](diffhunk://#diff-2fdd31c8eaeb05db626d15ffa6f31b34be3044212e22d6831e976afbab90cc86L21-R21) [[2]](diffhunk://#diff-f05b4db814aed56db52bbd7a3377a46369e19dd22f7b8dca3330fbac413d51a1L11-R12)
* Updated examples in …
> White label mod

- api/config/knexfile.ts
- api/graphql/schemas/user.schema.ts
- api/package-lock.json
- api/package.json
- api/repository/user.repository.ts
- api/server.ts
- api/services/authentication/change-password.service.ts
- api/services/authentication/get-user-logined.service.ts
- api/services/authentication/register.service.ts
- api/services/authentication/reset-password.service.ts
- app/src/containers/Profile/PasswordSetting.tsx
- app/src/queries/auth/changePassword.ts
This pull request introduces several changes to enhance authentication functionality, improve developer experience, and update dependencies. The most significant updates include adding support for tracking password changes, modifying GraphQL schemas and resolvers, replacing development tools, and refactoring code for cleaner implementation.
* [`api/config/knexfile.ts`](diffhunk://#diff-a6e78ecff33db8614136e6d1dea3f44e61269ba1f19334e3b76c3b5be6692df3L1-R18): Added a `typeCast` function to handle `TIMESTAMP` fields for the `password_changed_at` column in the `users` table.
* [`api/repository/user.repository.ts`](diffhunk://#diff-ef70fb76a3ffa8f1759dc3fbe66340f21ad9e45164f0d0afeb280de848251369R49): Extended the `UserProfile` type to include a `password_changed_at` field.
* …
> Security fixes/unfinished tasks

- api/routes/form.routes.ts
- Remove requireJsonContent middleware from GET /unsubscribe route
- Use correct unsubscribe controller function for GET requests
- Import unsubscribe function that handles query parameters and returns HTML
- Fixes 'Unsupported Media Type' error when users click email unsubscribe links
- Maintains separate POST /unsubscribe-newsletter route for API use
___
Bug fix
___
- Fix unsubscribe link from emails by removing JSON middleware
- Use correct controller function for GET unsubscribe route
- Import unsubscribe function for HTML response handling
- Resolve 'Unsupported Media Type' error for email links
___
```mermaid
flowchart LR
A["Email Link"] --> B["GET /unsubscribe"]
B --> C["Remove requireJsonContent"]
C --> D["Use unsubscribe controller"]
D --> E["Return HTML Response"]
```
<details> …
> fix: unsubscribe link from emails now works properly

- api/graphql/schemas/accessibilityReport.schema.ts
- api/helpers/accessibility.helper.ts
- api/services/accessibilityReport/accessibilityReport.service.ts
- api/services/accessibilityReport/enhancedProcessing.service.ts
- api/services/accessibilityReport/gptBatch.service.ts
- api/services/accessibilityReport/preprocessing.service.ts
- app/src/containers/Accessibility/AccessibilityIssuesGroup.tsx
- app/src/containers/Accessibility/AccessibilityReport.tsx
- app/src/containers/Accessibility/ReportView.tsx
- app/src/queries/accessibility/accessibility.ts
- app/src/queries/accessibility/fetchReportByR2Key.ts
- app/src/queries/accessibility/getAccessibilityReportByJobId.ts
- app/src/utils/translator.ts
Enhancement
___
- Add `wcag_code` field to accessibility report schemas
- Implement WCAG code parsing from new API response
- Update GraphQL queries to include WCAG codes
- Enhance PDF report generation with WCAG compliance
___
```mermaid
flowchart LR
API["New API Response"] --> Parser["parseWcagCode Function"]
Parser --> Schema["GraphQL Schema"]
Schema --> Query["Frontend Queries"]
Query --> Report["PDF Report Generation"]
Parser --> Fallback["Legacy Code Parsing"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td><strong>accessibilityReport.schema.ts</strong><dd><code>Add wcag_code field to GraphQL …
> Parsed codes from the new API

- api/controllers/form.controller.ts
- api/graphql/resolvers/user.resolver.ts
- api/graphql/schemas/user.schema.ts
- api/jobs/monthlyEmail.ts
- api/repository/user.repository.ts
- api/services/allowedSites/allowedSites.service.ts
- api/services/authentication/register.service.ts
- api/services/email/emailSequence.service.ts
- api/services/problemReport/reportProblem.ts
- api/services/user/update-user.service.ts
- app/src/components/Layout/Topbar.tsx
✨ Features:
- Add onboarding_emails_flag to user_notifications table
- Separate onboarding emails from general newsletter subscriptions
- Add user-controllable onboarding email preferences in UI
🔧 Backend Changes:
- Update user repository with onboarding email flag functions
- Modify registration service to create user_notifications records
- Update email sequence service to use user-based checks
- Fix unsubscribe functionality to set onboarding_emails_flag = 0
- Resolve database transaction lock timeout issues
🎨 Frontend Changes:
- Add onboarding emails toggle to notification settings UI
- Update GraphQL schema and resolvers for new field
- Enhance notification settings with proper UI controls
🚀 Migration Benefits:
- Users can now control onboarding emails independently
- Maintains …
> fix: migrate email sequence subscription from newsletter_subscribers to user_notifications

- api/controllers/form.controller.ts
- api/jobs/emailSequence.ts
- api/services/authentication/register.service.ts
- api/services/email/email.service.ts
- api/services/email/emailSequence.service.ts
- api/services/email/scheduledEmailTracker.service.ts
- Enhanced email service with Brevo scheduledAt support and cancellation
- Added scheduled email tracker service for monitoring and cancellation
- Implemented hybrid approach: Days 1-3 via Brevo, Days 7+ via enhanced cron
- Updated registration flow to schedule complete email sequence immediately
- Enhanced unsubscribe logic to cancel all scheduled Brevo emails
- Reduced cron job frequency to every 6 hours for fallback monitoring
- Added comprehensive error handling and graceful degradation
- Emails now arrive at exact 24-hour intervals from registration time
- Significantly reduced server load and improved scalability
___
Enhancement
___
- Implement 24-hour interval email scheduling with Brevo API
- Add hybrid approach: immediate scheduling (Days 1-3) + cron fallback
- Create scheduled …
> fix: implement 24-hour interval email scheduling with Brevo scheduling

- api/controllers/proof-of-effort.controller.ts
- api/controllers/widget-installation.controller.ts
- api/graphql/resolvers/widget.resolver.ts
Enhancement
___
- Centralized email validation logic across controllers
- Replaced inline regex with reusable validation function
- Standardized error response format for email validation
___
```mermaid
flowchart LR
A["Inline Email Regex"] --> B["Centralized emailValidation()"]
B --> C["proof-of-effort.controller.ts"]
B --> D["widget-installation.controller.ts"] 
B --> E["widget.resolver.ts"]
```
<tr>
<td>
<details>
<summary><strong>proof-of-effort.controller.ts</strong><dd><code>Replace inline email regex with validation function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> email validation function added

- api/graphql/resolvers/domainAnalysis.resolver.ts
- api/graphql/root.resolver.ts
- api/graphql/root.schema.ts
- api/graphql/schemas/domainAnalysis.schema.ts
- api/services/domainAnalysis/domainAnalysis.service.ts
- app/src/containers/AIInsights/AIInsights.tsx
- app/src/queries/domainAnalysis/analyzeDomain.ts
- app/src/routes/index.tsx
Enhancement
___
- Add AI Insights tab with domain heatmap analysis
- Implement GraphQL API for domain analysis service
- Create comprehensive UI for heatmap visualization
- Integrate external AI heatmap scanner API
___
```mermaid
flowchart LR
A["User Input"] --> B["Domain Analysis API"]
B --> C["External AI Scanner"]
C --> D["Heatmap Results"]
D --> E["Category Selection"]
E --> F["Heatmap Display"]
```
<tr>
<td>
<details>
<summary><strong>domainAnalysis.resolver.ts</strong><dd><code>Add domain analysis GraphQL resolver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Add new tab called ai insights

- app/src/components/Layout/Sidebar.tsx
- app/src/containers/AIInsights/AIInsights.tsx
- app/src/routes/index.tsx
Enhancement
___
- Added beta tags to AI Insights feature
- Implemented auto-scroll functionality for better UX
- Enhanced heatmap category display with descriptions
- Improved UI layout and icon sizing
___
```mermaid
flowchart LR
A["Sidebar Route"] -- "beta flag" --> B["Beta Tag Display"]
C["AI Insights Page"] -- "auto-scroll" --> D["Categories Section"]
C -- "category selection" --> E["Heatmap Display"]
F["Category Metadata"] -- "enhanced descriptions" --> G["Better UX"]
```
<tr>
<td>
<details>
<summary><strong>Sidebar.tsx</strong><dd><code>Add beta tag support to sidebar navigation</code>&nbsp; …
> Ui updated , beta tag added , auto scroll added

- app/src/containers/AIInsights/AIInsights.tsx
Enhancement
___
- Improved responsive layout for beta tag and title
- Changed flex direction from row to column-reverse on mobile
- Enhanced mobile-first design approach
___
```mermaid
flowchart LR
A["Mobile Layout"] -- "flex-col-reverse" --> B["Stacked Vertical"]
C["Desktop Layout"] -- "md:flex-row" --> D["Horizontal Row"]
B --> E["Beta Tag Above Title"]
D --> F["Beta Tag Next to Title"]
```
<tr>
<td>
<details>
<summary><strong>AIInsights.tsx</strong><dd><code>Enhanced responsive layout for header beta tag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Beta tag UI responsive

- api/services/email/emailSequence.service.ts
- api/services/user/update-user.service.ts
- Enhanced handleFailedScheduledEmails() to detect gaps of unlimited length instead of 7-day limit
- Added automatic email recovery/cancellation triggers when users toggle onboarding email preferences
- Improved gap detection logic to check all missing emails for each user since registration
- Fixed issue where users switching onboarding emails off/on would miss follow-up emails
- Maintains backward compatibility with existing email tracking system
Resolves email sequence gaps for production users like user 528 who toggle preferences
___
Bug fix, Enhancement
___
- Enhanced email sequence recovery to handle unlimited gap lengths
- Added automatic email recovery when users toggle onboarding preferences
- Improved gap detection logic for all missing emails since registration
- Fixed issue …
> fix: enhance email sequence recovery to handle unlimited gap lengths

- api/services/email/emailSequence.service.ts
- api/services/email/scheduledEmailTracker.service.ts
- Enhanced recoverMissedEmailsForUser() to handle cancelled scheduled emails
- Added intelligent recovery logic: immediate send for overdue emails, re-schedule for future emails
- Added getCancelledEmailsForUser() method to scheduledEmailTracker service
- Enhanced handleFailedScheduledEmails() with unlimited gap detection
- Fixed edge case where immediate email preference toggles failed to recover Day 1,2,3 emails
Fixes email sequence gaps when users toggle onboarding preferences off/on
___
Bug fix, Enhancement
___
- Enhanced email recovery system with intelligent scheduling logic
- Added unlimited gap detection for missed email sequences
- Implemented cancelled email recovery with re-scheduling capability
- Fixed edge cases in onboarding email preference toggles
___
```mermaid
flowchart …
```
> fix: Enhanced email recovery system with re-scheduling

- api/jobs/emailSequence.ts
- api/services/email/emailDeliveryStatus.service.ts
- api/services/email/emailSequence.service.ts
- api/services/email/scheduledEmailTracker.service.ts
- Remove immediate markEmailAsSent() for scheduled emails
- Add EmailDeliveryStatusService to sync actual delivery status
- Add delivery status checks every 30 minutes via cron
- Enhance duplicate prevention with isEmailAlreadyScheduled()
- Fix sent-emails.json to only update when emails are delivered
- Resolve email recovery gaps when users toggle preferences
This ensures scheduled emails are properly tracked and recovery logic correctly detects undelivered emails.
___
Bug fix, Enhancement
___
- Add email delivery status tracking service
- Prevent premature marking of scheduled emails as sent
- Implement 30-minute delivery status sync cron job
- Enhance duplicate prevention for scheduled emails
___
```mermaid
flowchart LR
A["Email Scheduled"] --> B["Delivery Status Check"]
B --> C["Email …
```
> Fix email delivery tracking: prevent premature sent marking

- app/src/containers/Installation/CodeContainer.tsx
Enhancement
___
- Added icon type customization option to widget installation
- Updated script tag to include `data-asw-icon-type` parameter
- Expanded grid layout to accommodate new icon selector
- Added dropdown for full/compact icon selection
___
```mermaid
flowchart LR
A["Widget Customization"] --> B["Position Selector"]
A --> C["Language Selector"]
A --> D["Icon Type Selector"]
D --> E["Full Icon Option"]
D --> F["Compact Icon Option"]
B --> G["Generated Script Tag"]
C --> G
D --> G
```
<tr>
<td>
<details>
<summary><strong>CodeContainer.tsx</strong><dd><code>Add icon type customization widget …
> Non intrusive text only widget

- app/src/containers/Installation/CodeContainer.tsx
Enhancement
___
- Added informational note about updating script tag
- Enhanced installation instructions with feature update guidance
___
```mermaid
flowchart LR
A["Installation Instructions"] --> B["Updated Text with Note"]
B --> C["User Guidance for Script Updates"]
```
<tr>
<td>
<details>
<summary><strong>CodeContainer.tsx</strong><dd><code>Enhanced installation instructions with update note</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/src/containers/Installation/CodeContainer.tsx
<ul><li>Added line break and informational note to installation instructions<br> <li> …
> Install page script Note

- api/jobs/emailSequence.ts
- api/services/email/emailDeliveryStatus.service.ts
- api/services/email/emailSequence.service.ts
- api/services/email/scheduledEmailTracker.service.ts
- api/services/user/update-user.service.ts
- Updated unsubscribeLink in emailSequence.service.ts lines 489 and 550
- Changed from frontendUrl to process.env.REACT_APP_BACKEND_URL
- Ensures unsubscribe functionality routes to proper API endpoint
___
Bug fix
___
- Fix unsubscribe URLs to use backend endpoint
- Changed from frontend URL to backend environment variable
- Ensures proper API routing for unsubscribe functionality
___
```mermaid
flowchart LR
A["Frontend URL"] -- "changed to" --> B["Backend URL"]
B --> C["Unsubscribe Endpoint"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>emailSequence.service.ts</strong><dd><code>Fix unsubscribe URL endpoint …
> Fix unsubscribe URLs to use backend endpoint

- api/repository/user.repository.ts
- api/services/email/emailSequence.service.ts
- Move top-level imports in emailSequence.service.ts for better performance
- Implement upsert patterns in user.repository.ts for robust database operations
- Add proper cutoff enforcement for users registered on/after August 14, 2025
- Improve daily email processing to check users with emails actually due today
- Add comprehensive error handling and logging for email sequence operations
___
Enhancement
___
- Implement upsert patterns for robust database operations
- Optimize email sequence processing for better performance
- Add proper cutoff enforcement for user registration dates
- Improve daily email processing to check users with emails due today
___
```mermaid
flowchart LR
A["Email Sequence Service"] --> B["Move Top-Level Imports"]
A --> C["Enhanced Daily Processing"]
C --> D["Check …
```
> Optimize email sequence processing and database operations

- api/services/accessibilityReport/gptBatch.service.ts
Enhancement
___
- Updated GPT batch processing to use configurable quality model
- Enhanced recommended action descriptions for better user-friendliness
- Replaced hardcoded model with environment variable configuration
___
```mermaid
flowchart LR
A["Hardcoded Model"] --> B["Environment Variable"]
C["Technical Descriptions"] --> D["User-Friendly Descriptions"]
B --> E["Configurable GPT Processing"]
D --> E
```
<tr>
<td>
<details>
<summary><strong>gptBatch.service.ts</strong><dd><code>Configure model and improve user descriptions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Quality model used for the gpt batch processing

- app/src/containers/Accessibility/AccessibilityReport.tsx
- app/src/containers/Accessibility/ReportView.tsx
- app/src/containers/ProofOfEffortToolkit/ProofOfEffortToolkit.tsx
Enhancement
___
• Implemented structured page breaks across PDF report generation to keep issue groups and related content together
• Added comprehensive category-based issue analysis with visual icons and progress bars for better accessibility insights
• Enhanced PDF layout with improved spacing, shadows, and visual hierarchy for better readability
• Integrated jsPDF autotable internal functions (`__createTable`, `__drawTable`) for better table rendering control
• Added extensive translation support for compliance status messages and warnings
• Redesigned PDF reports with smaller fonts, better spacing, and enhanced visual elements
• Removed legacy helper functions for image handling and issue styling in favor of new structured approach
___
```mermaid
flowchart LR
A["PDF Report …
```
> Structured page breaks added

- api/graphql/resolvers/user.resolver.ts
- api/graphql/schemas/user.schema.ts
- api/repository/user.repository.ts
- api/services/user/license-owner.service.ts
- app/src/containers/LicenseOwnerInfo/index.tsx
- app/src/locales/en.json
- app/src/queries/user/getLicenseOwnerInfo.ts
- app/src/queries/user/updateLicenseOwnerInfo.ts
- app/src/routes/index.tsx
Enhancement
___
- Add license owner information management functionality
- Create GraphQL queries and mutations for license data
- Implement responsive React form with country code selection
- Add new database fields for license owner details
___
```mermaid
flowchart LR
A["User Interface"] --> B["GraphQL Resolvers"]
B --> C["License Owner Service"]
C --> D["User Repository"]
D --> E["Database"]
F["React Form"] --> G["Apollo Client"]
G --> B
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td><strong>user.resolver.ts</strong><dd><code>Add license owner GraphQL resolvers</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> License owner info added

- api/graphql/resolvers/accessibilityReport.resolver.ts
- api/helpers/accessibility.helper.ts
- api/services/accessibilityReport/accessibilityReport.service.ts
- app/src/components/Common/WhatsNewModal.tsx
Enhancement
___
- Tech stack extraction from accessibility scanner API
- Screenshot extraction and storage improvements
- What's New modal cards made clickable
- Fallback logic for missing tech stack data
___
```mermaid
flowchart LR
A["Accessibility Scanner API"] --> B["Extract Tech Stack"]
A --> C["Extract Screenshots"]
B --> D["Fallback to Tech Stack API"]
C --> E["Store in siteImg"]
F["What's New Modal"] --> G["Clickable News Cards"]
```
<tr>
<td>
<details>
<summary><strong>accessibilityReport.resolver.ts</strong><dd><code>Tech stack extraction with fallback logic</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> reapplied reverted changes - links added to cards, no openner/noreffer , analyzer

- api/controllers/chat.controller.ts
- api/routes/chat.routes.ts
- api/routes/index.ts
- app/src/containers/Accessibility/FloatingChatbot.tsx
- app/src/containers/Accessibility/ReportView.tsx
- Resolved 'WCAG: N/A' issue in ReportView by ensuring  is correctly passed and displayed.
- Improved chatbot UI by fixing the blinking issue on the send button.
- Enhanced overall user experience for accessibility issue reporting and interaction.
___
Bug fix, Enhancement
___
- Fixed WCAG display issue in ReportView
- Removed send button animation blinking
- Improved accessibility reporting user experience
___
```mermaid
flowchart LR
A["ReportView"] -- "Fix WCAG field" --> B["Display issue.message"]
C["FloatingChatbot"] -- "Remove animation" --> D["Send button styling"]
```
<tr>
<td>
<details> …
> Fix WCAG issue and improve UI/UX for chatbot and report view

- api/jobs/monthlyEmail.ts
- api/services/allowedSites/allowedSites.service.ts
Bug fix
___
- Fixed issue count calculation to include both AXE and HTML_CS results
- Reduced monthly email concurrency limit from 10 to 2 tasks
___
```mermaid
flowchart LR
A["HTML_CS Issues"] --> C["Combined Count Calculation"]
B["AXE Issues"] --> C
C --> D["Email Template Data"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>allowedSites.service.ts</strong><dd><code>Combine AXE and HTML_CS issue counts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Identified Issues count fixed will now use axe too

- api/controllers/shopify.controller.ts
🔒 SECURITY IMPROVEMENTS:
1. BUFFER VALIDATION: Added explicit Buffer type checking
- Fails fast if req.body is not a Buffer
- Prevents unreliable JSON reconstruction for HMAC verification
- Clear error message for middleware configuration issues
2. REMOVED UNRELIABLE FALLBACK:
- Eliminated dangerous JSON.stringify() fallback logic
- Prevents false positive HMAC verification due to formatting differences
- Ensures HMAC is calculated from exact bytes received
3. TYPE SAFETY:
- TypeScript guarantee that rawBody is Buffer type
- No more conditional Buffer assignment logic
- Direct assignment after validation
🛡️ SECURITY RATIONALE:
The previous fallback logic could incorrectly verify HMACs when JSON formatting differed between original payload and reconstructed string. This improvement ensures …
> security: Improve HMAC verification with explicit Buffer validation
